
services:
  - type: web
    name: vcf-cleaner
    runtime: python
    buildCommand: |
      pip install -r requirements.txt
      python manage.py migrate
    startCommand: gunicorn backend.wsgi:application 
    envVars:
      - key: DEBUG
        value: "False"
      - key: SECRET_KEY
        generateValue: true
      - key: ALLOWED_HOSTS
        value: ".onrender.com vcf-cleaner.onrender.com"
      - key: CORS_ALLOWED_ORIGINS
        value: "https://vcf-cleaner.vercel.app/ http://localhost:3000"