# Generated by Django 5.2 on 2025-04-03 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VcfFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_file', models.FileField(upload_to='vcfs/')),
                ('cleaned_file', models.FileField(blank=True, null=True, upload_to='cleaned_vcfs/')),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
